version: '3.8'

services:
  # Local DynamoDB service
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    volumes:
      - "./dynamodb-data:/home/dynamodblocal"
    working_dir: /home/dynamodblocal
    networks:
      - socialsports-network

  # Spring Boot application
  app:
    build: .
    container_name: socialsports-app
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-local
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=eu-west-1
      - WHATSAPP_BUSINESS_PHONE_NUMBER_ID=${WHATSAPP_BUSINESS_PHONE_NUMBER_ID}
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN}
    networks:
      - socialsports-network

networks:
  socialsports-network:
    driver: bridge