version: '3.8'

services:
  # Local DynamoDB service
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal"
    volumes:
      - "./dynamodb-data:/home/dynamodblocal"
    working_dir: /home/dynamodblocal
    networks:
      - socialsports-network

  # Spring Boot application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socialsports-app
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-local
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AWS_DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_REGION=eu-west-1
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - WHATSAPP_BUSINESS_PHONE_NUMBER_ID=${WHATSAPP_BUSINESS_PHONE_NUMBER_ID}
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN}
    networks:
      - socialsports-network

networks:
  socialsports-network:
    driver: bridge